### ISSUE TITLE
Snake case

### ISSUE THREAD

**Issue by benjie** [catherinedevlin/opensourceshakespeare#4]
Hi Catherine, thanks for this handy repo! I've forked it to turn it into a demo repo for my open source project, PostGraphile. (Work is still ongoing.)

I notice you have column definitions such as `workID`, `longTitle`, etc. However because PostgreSQL lowercases any identifiers that are not escaped in double quotes this comes out as: `workid`, `longtitle`, etc. This means that I cannot expose the intent automatically via PostGraphile. If the table definition were to use snake_case like this:

```sql
CREATE TABLE work
  ( work_id    VARCHAR(32) PRIMARY KEY,
    title     VARCHAR(32) NOT NULL,
    long_title VARCHAR(64) NOT NULL,
    year      INTEGER NOT NULL,
    genre_type VARCHAR(1) NOT NULL,
    notes     TEXT,
    source    VARCHAR(16) NOT NULL,
    total_words      INTEGER NOT NULL,
    total_paragraphs INTEGER NOT NULL
  );
```

PostGraphile could automatically detect where the word boundaries are and expose the columns correctly. I've made these changes in my fork:

https://github.com/benjie/opensourceshakespeare

along with a number of other things specific to my use case (hence a direct PR is (probably) not suitable).

I was wondering if you would like me to send a PR for just the database changes (or maybe the database changes and fetch/load/dump scripts). This would be a breaking change since the table columns will have been renamed.

If you're not interested, please feel free to close this issue, just wanted to share my changes in the spirit of open source.

**Comment by catherinedevlin** [comment]
Hi, Benjie!   I'm so sorry, I've never figured out how to get my github notifications without being swamped with ones I don't care about and I end up not noticing them.

I do like your change and would happy to take the PR.  In fact, I played with your version and would be happy to take all your changes, with just one exception: I do want to import into the public schema, rather than the separate "shakespeare" schema like you do; I think it's less confusing for beginners.  But if you make your PR I can apply that change myself.

Thanks!

**Comment by benjie** [comment]
Sure thing; I've raised #5 without the schema change. The script currently leverages the fact we can drop the entire shakespeare schema and recreate it without having to recreate the DB. You can do the same with the public schema, but it's a little more work because you have to restore permissions, etc; so you might want to replace that part with dropping and recreating the DB instead? Anyway, I've left that up to you to do as you mentioned above :+1: 

Thanks again!
